_target_: models.action_ae.discretizers.k_means.KMeansDiscretizer
num_bins: 64 # same as number of clusters, can be set
action_dim: ${env.action_dim}
device: ${device}
predict_offsets: True # has to be true to recontruct the continous actions
