defaults:
  - _self_
  - encoder: identity
  - action_ae: discretizers/k_means_pusht_best
  - env: pusht
  - state_prior: mingpt_pusht_best
  - env_vars: env_vars

lazy_init_models: True

device: mps # can be adapted based on device like cuda
seed: 42
load_dir: ${env.load_dir}

# Length of history
window_size: 14 # need to be same exactly as in train_pusht.yaml

# testing details
train_fraction: 0.95
test_batch_size: 1
test_num_workers: 8

# Environment running setup
num_eval_eps: 206 # for now it is number of episodes in pushT
action_batch_size: 1
num_eval_steps: 300 # number of evaluation steps for each episode
use_state_prior: True # flag to use the trained prior
enable_offsets: True # flag to enable offsets prediction during action reconstruction
action_update_every: 1
flatten_obs: False
enable_render: False

# Plotting setup
plot_interactions: False # NOT implemented
start_from_seen: False # NOT implemented
record_video: True # flag to record videos in the /exp_local directory

# Wandb setup
project: behavior_transformer_repro_test
experiment: pusht_eval

hydra:
  job:
    override_dirname: ${experiment}
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${experiment}
    subdir: ${hydra.job.num}
