name: PushT-v0
obs_dim: 2
action_dim: 2
action_min: null
action_max: null

load_dir: "/Users/satyabrata/Desktop/projects/behaviour_transformer_policy/exp_local/2025.08.02/230406_pusht_train"

workspace:  # This is the workspace for the PushT environment
  _target_: workspaces.push_t.PushTWorkspace

dataset_fn:
  _target_: dataloaders.trajectory_loader.get_pusht_train_val  # Function to load the dataset
  dataset_path: ${env_vars.datasets.pusht}
  window_size: ${window_size}
